=== sheree2591/WBA2/WBA2/src/org/example/aufgabe_2_d/Aufgabe_3_d.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Aufgabe_2_d" xmlns:tns="http://www.example.org/Aufgabe_2_d" elementFormDefault="qualified">
<xs:element name ="rezept">
	<xs:complexType>
		<xs:sequence>

			<!-- <xs:element name="titel" type="string"/>
			<xs:element name="zutaten" type="zutaten_type"/>
			<xs:element name="zubereitung" type="zubereitung_type"/>
			<xs:element name="kommentar" type="kommentar_type"/>  -->

			<xs:element name="Allgemein">
			<xs:complexType>
				<xs:sequence>
				<xs:element name ="titel" type ="xs:string"/>
				<xs:element name ="zutaten" type ="xs:string"/>
				<xs:element name ="kommentar" type ="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			</xs:element>
			
			<xs:element name="Zutaten">
			<xs:complexType>
				<xs:sequence>
					<xs:element name ="name" type ="xs:string"/>
					<xs:element name ="anzahl" type ="xs:integer"/>
					<xs:element name ="einheit" type ="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			</xs:element>
			
			<xs:element name="Zubereitung">
			<xs:complexType>
				<xs:sequence>
					<xs:element name ="arbeitszeit" type ="xs:integer"/>
					<xs:element name ="schwierigkeitsgrad" type ="xs:string"/>
					<xs:element name ="brennwert" type ="xs:integer"/>
					<xs:element name ="beschreibung" type ="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			</xs:element>
			
			<xs:element name="Kommentar">
			<xs:complexType>
				<xs:sequence>
					<xs:element name ="name" type ="xs:string"/>
					<xs:element name ="datum" type = "xs:date"/>
					<xs:element name ="uhrzeit" type ="xs:integer"/>
					<xs:element name ="text" type ="xs:string"/>
					<xs:element name ="antwort" type ="xs:string"/>
					<xs:element name ="text_2" type ="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			</xs:element>

</xs:sequence>	
</xs:complexType>
</xs:element>
</xs:schema>

=== sheree2591/WBA2/WBA2/bin/Aufgabe_3_d_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rezept xmlns="http://www.example.org/Aufgabe_2_d" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Aufgabe_2_d Aufgabe_3_d.xsd ">
  <Allgemein>
    <titel> Spaghetti Bolognese </titel>
    <zutaten>Zutaten</zutaten>
    <kommentar>Kommentar</kommentar>
  </Allgemein>
  <Zutaten>
    <name> Spaghetti </name>
    <anzahl> 500 </anzahl>
    <einheit> Gramm </einheit>
    <name> Hackfleisch </name>
    <anzahl> 500 </anzahl>
    <einheit> Gramm </einheit>
    <name> Zwiebeln </name>
    <anzahl> 1 </anzahl>
    <einheit> St√ºck </einheit>
  </Zutaten>
  <Zubereitung>
    <arbeitszeit> 30 </arbeitszeit>
    <schwierigkeitsgrad> einfach </schwierigkeitsgrad>
    <brennwert> 400 </brennwert>
    <beschreibung> Zuerst die Zwiebel kleinschneiden und glasig braten..</beschreibung>
  </Zubereitung>
  <Kommentar>
    <name> Peterchen </name>
    <datum>2013-08-23</datum>
    <uhrzeit> 12.30 </uhrzeit>
    <text> Super Rezept </text>
  </Kommentar>
</rezept>

=== sheree2591/WBA2/WBA2/bin/Aufgabe_3_d.xml
<?xml version="1.0" encoding="UTF-8"?>
<rezept xmlns="http://www.example.org/Aufgabe_2_d" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Aufgabe_2_d Aufgabe_3_d.xsd ">
  <Allgemein>
    <titel> Lasagne </titel>
    <zutaten>Zutaten</zutaten>
    <kommentar>Kommentar</kommentar>
  </Allgemein>
  <Zutaten>
    <name> Lasagneplatten </name>
    <anzahl> 20 </anzahl>
    <einheit>Stück</einheit>
    <name> Hackfleisch </name>
    <anzahl> 500 </anzahl>
    <einheit> Gramm </einheit>
    <name> Zwiebeln </name>
    <anzahl> 1 </anzahl>
    <einheit> Stück </einheit>
  </Zutaten>
  <Zubereitung>
    <arbeitszeit> 45 </arbeitszeit>
    <schwierigkeitsgrad> einfach </schwierigkeitsgrad>
    <brennwert> 580</brennwert>
    <beschreibung> Zuerst die Zwiebel kleinschneiden und glasig braten..</beschreibung>
  </Zubereitung>
  <Kommentar>
    <name> Hans Wurst </name>
    <datum>2001-01-01</datum>
    <uhrzeit> 12.30 </uhrzeit>
    <text> schmeckt toll </text>
    <antwort>
    <text_2> danke </text_2>
    </antwort>
  </Kommentar>
</rezept>
