=== sheree2591/WBA2/WBA2/bin/Aufgabe_3/Aufgabe_3_d.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Rezepte">
<xs:complexType>
<xs:sequence>
<xs:element name="Rezept" maxOccurs="unbounded" minOccurs="1">
<xs:complexType>
<xs:sequence>
	<xs:element name="Rezeptname" type="xs:string"/>
	<xs:element name="Autor" type="xs:string"/>

	<xs:element name="Zutaten" maxOccurs="1" minOccurs="1">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Zutat" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
	                       <xs:element name="Name" type="xs:string" maxOccurs="1"
	                                   minOccurs="1"/>
	                       <xs:element name="Menge" type="xs:float" maxOccurs="1"
	                                   minOccurs="0"/>
	                   </xs:sequence>
	                   <xs:attribute name="Einheit" default="g">
	                       <xs:simpleType>
	                            <xs:restriction base="xs:string">
	                                <xs:enumeration value="g"/>
	                                <xs:enumeration value="Pck."/>
	                                <xs:enumeration value="EL"/>
	                                <xs:enumeration value="ml"/>
	                                <xs:enumeration value="Prise"/>
	                                <xs:enumeration value="Dose"/>
	                                <xs:enumeration value="TL"/>
	                                <xs:enumeration value="Pkt."/>
	                                <xs:enumeration value="Stk." />
	                                <xs:enumeration value="Flasche"/>
	                            </xs:restriction>
	                        </xs:simpleType>
	                    </xs:attribute>
	                </xs:complexType>
	            </xs:element>
	        </xs:sequence>
	    </xs:complexType>
	</xs:element>


	<xs:element name="Portionen">
		<xs:simpleType>
 		   <xs:restriction base="xs:integer">
      			<xs:minInclusive value="0"/>
      			<xs:maxInclusive value="20"/>
    		</xs:restriction>
  		</xs:simpleType>
	</xs:element>


	<xs:element name="Zubereitung">
		<xs:complexType>
			<xs:sequence>	
				<xs:element name="Arbeitszeit">
					<xs:complexType>
                          <xs:sequence>
                               <xs:element name="Dauer" type="xs:integer"/>
                         </xs:sequence>
                         <xs:attribute name="Einheit">
                             <xs:simpleType>
                                <xs:restriction base="xs:string">
                                        <xs:enumeration value="std"/>
										<xs:enumeration value="min"/>
								</xs:restriction>
							</xs:simpleType>                         
						</xs:attribute>
					</xs:complexType>
                </xs:element>
				<xs:element name="Schwierigkeitsgrad" type="xs:string"/>
				<xs:element name="Brennwert-p.P" type="xs:integer"/>
				<xs:element name="VorgÃ¤nge" type="xs:string"/>	
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Kommentieren">
	<xs:complexType>	
		<xs:sequence>
	            <xs:element name="Kommentar">
	                <xs:complexType>
	                    <xs:attribute name="Name" type="xs:string"/>
	                    <xs:attribute name="Datum" type="xs:date"/>
	                    <xs:attribute name="Zeit" type="xs:time"/>
	                    <xs:attribute name="Kommentare" type="xs:string"/>
	                </xs:complexType>
	            </xs:element>
	        </xs:sequence>
	    </xs:complexType>
	</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== sheree2591/WBA2/WBA2/src/Aufgabe_3/Aufgabe_3_d.xml
<?xml version="1.0" encoding="UTF-8"?>
<Rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe_3_d.xsd">
  <Rezept>
    <Rezeptname>Lasagne</Rezeptname>
    <Autor>Peggy</Autor>
    <Zutaten>
      <Zutat>
        <Name>Lasagneplatten</Name>
      </Zutat>
    </Zutaten>
    <Portionen>2</Portionen>
    <Zubereitung>
      <Arbeitszeit>
        <Dauer>45</Dauer>
      </Arbeitszeit>
      <Schwierigkeitsgrad>mittel</Schwierigkeitsgrad>
      <Brennwert-p.P>580</Brennwert-p.P>
      <Vorgänge>Zwiebeln kleinschneiden und glasig braten.
      Anschließend Hackfleisch hinzugeben und braten lassen.</Vorgänge>
    </Zubereitung>
    <Kommentieren>
      <Kommentar/>
    </Kommentieren>
  </Rezept>
</Rezepte>

=== sheree2591/WBA2/WBA2/bin/Aufgabe_3/Aufgabe_3_d2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe_3_d.xsd">
  <Rezept>
    <Rezeptname>Paprika-Sahne Hähnchen</Rezeptname>
    <Autor>Gandalf</Autor>
    <Zutaten>
      <Zutat>
        <Name>Hähnchenbrust</Name>
        <Anzahl> 400 </Anzahl>
        <Einheit> gramm </Einheit>
      </Zutat>
      <Zutat>
      	<Name> Schlagsahne</Name>
      	<Anzahl> 250 </Anzahl>
        <Einheit> ml </Einheit>
      </Zutat>
    </Zutaten>
    <Portionen>3</Portionen>
    <Zubereitung>
      <Arbeitszeit>
        <Dauer>30</Dauer>
      </Arbeitszeit>
      <Schwierigkeitsgrad>einfach</Schwierigkeitsgrad>
      <Brennwert-p.P>470</Brennwert-p.P>
      <Vorgänge>Hähnchenbrust in ein Backblech legen
      Paprika-Sahne Soße über Hähnchenbrust gießen. </Vorgänge>
    </Zubereitung>
    <Kommentieren>
      <Kommentar/>
    </Kommentieren>
  </Rezept>
</Rezepte>
